# SKIE Configuration
# https://skie.touchlab.co/configuration

[features]
# Improved coroutines interop
coroutines_interop = true

# Improved Flow interop
flows = true

# Improved sealed class interop
sealed_enums = true

# Improved suspend function interop
suspend_functions = true

# Add completion handlers for suspend functions
suspend_functions_completion_handlers = true

[features.coroutines_interop]
# Coroutines settings
enabled = true

[features.flows]
# Flow settings
enabled = true

[features.sealed_enums]
# Sealed class settings
enabled = true

[features.suspend_functions]
# Suspend function settings
enabled = true

[features.suspend_functions_completion_handlers]
# Completion handlers settings
enabled = true
