package dev.androidbroadcast.featured.gradle

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FlagRegistrarGeneratorTest {
    @Test
    fun `generates package declaration`() {
        val source = FlagRegistrarGenerator.generate(emptyList(), packageName = "com.example.generated")
        assertContains(source, "package com.example.generated")
    }

    @Test
    fun `generates FlagRegistry import`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "import dev.androidbroadcast.featured.registry.FlagRegistry")
    }

    @Test
    fun `generates GeneratedFlagRegistrar object`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "object GeneratedFlagRegistrar")
    }

    @Test
    fun `generates public object modifier`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "public object GeneratedFlagRegistrar")
    }

    @Test
    fun `generates register function`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "public fun register()")
    }

    @Test
    fun `generates empty register body when no entries`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertFalse(
            source.contains("FlagRegistry.register("),
            "Expected no register calls for empty entries, got:\n$source",
        )
    }

    @Test
    fun `generates register call for entry with owner`() {
        val entries =
            listOf(
                LocalFlagEntry(
                    key = "new_checkout",
                    defaultValue = "false",
                    type = "Boolean",
                    moduleName = ":checkout",
                    propertyName = "newCheckout",
                    ownerName = "NewCheckoutFlags",
                ),
            )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(NewCheckoutFlags.newCheckout)")
    }

    @Test
    fun `generates register call for top-level entry without owner`() {
        val entries =
            listOf(
                LocalFlagEntry(
                    key = "dark_theme",
                    defaultValue = "true",
                    type = "Boolean",
                    moduleName = ":app",
                    propertyName = "darkTheme",
                    ownerName = null,
                ),
            )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(darkTheme)")
    }

    @Test
    fun `generates register calls for multiple entries`() {
        val entries =
            listOf(
                LocalFlagEntry(
                    key = "flag_a",
                    defaultValue = "false",
                    type = "Boolean",
                    moduleName = ":app",
                    propertyName = "flagA",
                    ownerName = "MyFlags",
                ),
                LocalFlagEntry(
                    key = "flag_b",
                    defaultValue = "true",
                    type = "Boolean",
                    moduleName = ":app",
                    propertyName = "flagB",
                    ownerName = "MyFlags",
                ),
            )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(MyFlags.flagA)")
        assertContains(source, "FlagRegistry.register(MyFlags.flagB)")
    }

    @Test
    fun `generates TODO comment for entry with blank property name`() {
        val entries =
            listOf(
                LocalFlagEntry(
                    key = "legacy_flag",
                    defaultValue = "false",
                    type = "Boolean",
                    moduleName = ":app",
                    propertyName = "",
                    ownerName = null,
                ),
            )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "// TODO: register flag 'legacy_flag'")
        assertFalse(
            source.contains("FlagRegistry.register()"),
            "Should not emit empty register call for blank property name",
        )
    }

    @Test
    fun `generated source contains auto-generated warning comment`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "Auto-generated by the Featured Gradle plugin")
    }

    @Test
    fun `uses default package name when not specified`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "package dev.androidbroadcast.featured.generated")
    }

    @Test
    fun `generates valid kotlin structure — braces are balanced`() {
        val entries =
            listOf(
                LocalFlagEntry(
                    key = "flag",
                    defaultValue = "false",
                    type = "Boolean",
                    moduleName = ":app",
                    propertyName = "myFlag",
                    ownerName = "Flags",
                ),
            )
        val source = FlagRegistrarGenerator.generate(entries)
        val openBraces = source.count { it == '{' }
        val closeBraces = source.count { it == '}' }
        assertTrue(
            openBraces == closeBraces && openBraces >= 2,
            "Expected balanced braces (≥2 pairs), open=$openBraces close=$closeBraces in:\n$source",
        )
    }
}
