package dev.androidbroadcast.featured.gradle

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class FlagRegistrarGeneratorTest {
    @Test
    fun `generates package declaration`() {
        val source = FlagRegistrarGenerator.generate(emptyList(), packageName = "com.example.generated")
        assertContains(source, "package com.example.generated")
    }

    @Test
    fun `generates FlagRegistry import`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "import dev.androidbroadcast.featured.registry.FlagRegistry")
    }

    @Test
    fun `generates public GeneratedFlagRegistrar object`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "public object GeneratedFlagRegistrar")
    }

    @Test
    fun `generates public register function`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "public fun register()")
    }

    @Test
    fun `generates empty register body when no entries`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertFalse(source.contains("FlagRegistry.register("), "No register calls for empty entries")
    }

    @Test
    fun `generates GeneratedLocalFlags import for local flag`() {
        val entries = listOf(localEntry("dark_mode", "darkMode"))
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "import dev.androidbroadcast.featured.generated.${LocalFlagEntry.GENERATED_LOCAL_OBJECT}")
    }

    @Test
    fun `generates GeneratedRemoteFlags import for remote flag`() {
        val entries = listOf(remoteEntry("promo_banner", "promoBanner"))
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "import dev.androidbroadcast.featured.generated.${LocalFlagEntry.GENERATED_REMOTE_OBJECT}")
    }

    @Test
    fun `does not generate local import when no local flags`() {
        val entries = listOf(remoteEntry("promo", "promo"))
        val source = FlagRegistrarGenerator.generate(entries)
        assertFalse(source.contains(LocalFlagEntry.GENERATED_LOCAL_OBJECT + "\n"))
    }

    @Test
    fun `generates register call referencing GeneratedLocalFlags for local flag`() {
        val entries = listOf(localEntry("dark_mode", "darkMode"))
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(${LocalFlagEntry.GENERATED_LOCAL_OBJECT}.darkMode)")
    }

    @Test
    fun `generates register call referencing GeneratedRemoteFlags for remote flag`() {
        val entries = listOf(remoteEntry("promo_banner", "promoBanner"))
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(${LocalFlagEntry.GENERATED_REMOTE_OBJECT}.promoBanner)")
    }

    @Test
    fun `generates register calls for mixed local and remote entries`() {
        val entries = listOf(
            localEntry("dark_mode", "darkMode"),
            remoteEntry("promo_banner", "promoBanner"),
        )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "FlagRegistry.register(${LocalFlagEntry.GENERATED_LOCAL_OBJECT}.darkMode)")
        assertContains(source, "FlagRegistry.register(${LocalFlagEntry.GENERATED_REMOTE_OBJECT}.promoBanner)")
    }

    @Test
    fun `generates TODO comment for blank property name`() {
        val entries = listOf(
            LocalFlagEntry(key = "legacy_flag", defaultValue = "false", type = "Boolean", moduleName = ":app"),
        )
        val source = FlagRegistrarGenerator.generate(entries)
        assertContains(source, "// TODO: register flag 'legacy_flag'")
        assertFalse(source.contains("FlagRegistry.register()"))
    }

    @Test
    fun `generated source contains auto-generated comment`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "Auto-generated by Featured Gradle Plugin")
    }

    @Test
    fun `uses default package name when not specified`() {
        val source = FlagRegistrarGenerator.generate(emptyList())
        assertContains(source, "package dev.androidbroadcast.featured.generated")
    }

    @Test
    fun `generated source has balanced braces`() {
        val entries = listOf(localEntry("flag", "flag"))
        val source = FlagRegistrarGenerator.generate(entries)
        val open = source.count { it == '{' }
        val close = source.count { it == '}' }
        assertTrue(open == close && open >= 2, "Expected balanced braces, open=$open close=$close")
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private fun localEntry(key: String, propertyName: String) =
        LocalFlagEntry(
            key = key, defaultValue = "false", type = "Boolean", moduleName = ":app",
            propertyName = propertyName, flagType = LocalFlagEntry.FLAG_TYPE_LOCAL,
        )

    private fun remoteEntry(key: String, propertyName: String) =
        LocalFlagEntry(
            key = key, defaultValue = "false", type = "Boolean", moduleName = ":app",
            propertyName = propertyName, flagType = LocalFlagEntry.FLAG_TYPE_REMOTE,
        )
}
