package dev.androidbroadcast.featured.gradle

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertTrue

class IosConstValGeneratorTest {
    @Test
    fun `generates empty string when entries list is empty`() {
        val result = IosConstValGenerator.generate(emptyList())
        assertTrue(result.isBlank(), "Expected blank output for empty entries, got: '$result'")
    }

    @Test
    fun `generated file contains auto-generated header comment`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "newCheckoutEnabled", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "Auto-generated by featured-gradle-plugin")
    }

    @Test
    fun `generated file contains correct package declaration`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "newCheckoutEnabled", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "package dev.androidbroadcast.featured.generated")
    }

    @Test
    fun `generates actual const val for boolean flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "newCheckoutEnabled", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val newCheckoutEnabled: Boolean = false")
    }

    @Test
    fun `generates actual const val for boolean flag with true default`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "darkModeEnabled", defaultValue = "true", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val darkModeEnabled: Boolean = true")
    }

    @Test
    fun `generates actual const val for Int flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "retryCount", defaultValue = "3", type = "Int", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val retryCount: Int = 3")
    }

    @Test
    fun `generates actual const val for String flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "serverUrl", defaultValue = "https://example.com", type = "String", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, """public actual const val serverUrl: String = "https://example.com"""")
    }

    @Test
    fun `generates actual const val for Double flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "threshold", defaultValue = "0.5", type = "Double", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val threshold: Double = 0.5")
    }

    @Test
    fun `generates actual const val for Long flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "timeoutMs", defaultValue = "5000", type = "Long", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val timeoutMs: Long = 5000")
    }

    @Test
    fun `generates actual const val for Float flag`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "ratio", defaultValue = "0.75f", type = "Float", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val ratio: Float = 0.75f")
    }

    @Test
    fun `generates multiple declarations for multiple entries`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "flagA", defaultValue = "false", type = "Boolean", moduleName = ":app"),
                LocalFlagEntry(key = "flagB", defaultValue = "true", type = "Boolean", moduleName = ":app"),
                LocalFlagEntry(key = "retryCount", defaultValue = "3", type = "Int", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "public actual const val flagA: Boolean = false")
        assertContains(result, "public actual const val flagB: Boolean = true")
        assertContains(result, "public actual const val retryCount: Int = 3")
    }

    @Test
    fun `does not emit do-not-edit notice without header`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "flag", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generate(entries)
        assertContains(result, "do not edit")
    }

    @Test
    fun `generateExpect produces expect declarations for commonMain`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "newCheckoutEnabled", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generateExpect(entries)
        assertContains(result, "public expect val newCheckoutEnabled: Boolean")
    }

    @Test
    fun `generateExpect produces expect declarations for multiple entries`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "flagA", defaultValue = "false", type = "Boolean", moduleName = ":app"),
                LocalFlagEntry(key = "retryCount", defaultValue = "3", type = "Int", moduleName = ":core"),
            )
        val result = IosConstValGenerator.generateExpect(entries)
        assertContains(result, "public expect val flagA: Boolean")
        assertContains(result, "public expect val retryCount: Int")
    }

    @Test
    fun `generateExpect contains package and header`() {
        val entries =
            listOf(
                LocalFlagEntry(key = "flag", defaultValue = "false", type = "Boolean", moduleName = ":app"),
            )
        val result = IosConstValGenerator.generateExpect(entries)
        assertContains(result, "package dev.androidbroadcast.featured.generated")
        assertContains(result, "Auto-generated by featured-gradle-plugin")
    }

    @Test
    fun `generateExpect is empty when entries list is empty`() {
        val result = IosConstValGenerator.generateExpect(emptyList())
        assertTrue(result.isBlank(), "Expected blank output for empty entries, got: '$result'")
    }
}
