package dev.androidbroadcast.featured.gradle.aggregation

import dev.androidbroadcast.featured.gradle.manifest.FeaturedManifest
import dev.androidbroadcast.featured.gradle.manifest.FlagDescriptor
import dev.androidbroadcast.featured.gradle.manifest.ValueType

/**
 * Generates `GeneratedFeaturedRegistry.kt` source from the aggregated [FeaturedManifest] list.
 *
 * KMP-safe: imports only `dev.androidbroadcast.featured.ConfigParam`. Enum types are referenced
 * inline by their fully-qualified name in both the `ConfigParam<...>` type argument and the
 * `defaultValue = ...` expression — no separate enum imports are emitted.
 *
 * Output determinism: descriptors are sorted by `(modulePath, key)` over the flattened
 * list before generation, so the output is identical regardless of the order in which
 * Gradle resolves the manifest artifacts.
 */
internal object GeneratedFeaturedRegistryGenerator {
    private const val CONFIG_PARAM_IMPORT = "dev.androidbroadcast.featured.ConfigParam"

    /**
     * Generates the full `GeneratedFeaturedRegistry.kt` source text.
     *
     * @param manifests Aggregated manifests from all producer modules.
     * @param packageName Package declared at the top of the generated file.
     * @return Complete Kotlin source as a single [String].
     */
    fun generate(
        manifests: List<FeaturedManifest>,
        packageName: String,
    ): String {
        val sorted =
            manifests
                .flatMap { manifest -> manifest.flags.map { flag -> manifest.modulePath to flag } }
                .sortedWith(compareBy({ it.first }, { it.second.key }))

        return buildString {
            appendLine("// Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine("package $packageName")
            appendLine()
            appendLine("import $CONFIG_PARAM_IMPORT")
            appendLine()
            appendLine("public object $FEATURED_REGISTRY_OBJECT {")
            if (sorted.isEmpty()) {
                appendLine("    public val all: List<ConfigParam<*>> = emptyList()")
            } else {
                appendLine("    public val all: List<ConfigParam<*>> = listOf(")
                sorted.forEach { (modulePath, descriptor) ->
                    if (descriptor.valueType == ValueType.ENUM) {
                        requireNotNull(descriptor.enumTypeFqn) {
                            "enumTypeFqn must be non-null for ENUM flag '${descriptor.key}' in module '$modulePath'"
                        }
                    }
                    val typeArg = descriptor.valueType.toKotlinTypeName(descriptor.enumTypeFqn)
                    val defaultLiteral = descriptor.toDefaultLiteral()
                    val args =
                        buildList {
                            add("key = \"${escapeKotlinString(descriptor.key)}\"")
                            add("defaultValue = $defaultLiteral")
                            if (descriptor.description != null) add("description = \"${escapeKotlinString(descriptor.description)}\"")
                            if (descriptor.category != null) add("category = \"${escapeKotlinString(descriptor.category)}\"")
                        }
                    // Kotlin accepts trailing commas in listOf() — always emit one for uniform diffs.
                    appendLine("        ConfigParam<$typeArg>(${args.joinToString(", ")}),")
                }
                appendLine("    )")
            }
            append("}")
        }
    }
}

/**
 * Maps this [ValueType] to the Kotlin type name used in the `ConfigParam<T>` type argument.
 *
 * For [ValueType.ENUM], [enumTypeFqn] must be non-null; it is used as the full type reference.
 */
private fun ValueType.toKotlinTypeName(enumTypeFqn: String?): String =
    when (this) {
        ValueType.BOOLEAN -> {
            "Boolean"
        }

        ValueType.INT -> {
            "Int"
        }

        ValueType.LONG -> {
            "Long"
        }

        ValueType.FLOAT -> {
            "Float"
        }

        ValueType.DOUBLE -> {
            "Double"
        }

        ValueType.STRING -> {
            "String"
        }

        ValueType.ENUM -> {
            requireNotNull(enumTypeFqn) {
                "enumTypeFqn must be non-null for ValueType.ENUM"
            }
        }
    }

/**
 * Escapes a bare string value so it is safe to embed inside a Kotlin double-quoted string literal.
 *
 * Escape order matters: `\` must be processed first to avoid double-escaping characters
 * introduced by subsequent replacements.
 *
 * - `\`  → `\\`        (backslash)
 * - `"`  → `\"`        (double-quote)
 * - `$`  → `${'$'}`    (prevents Kotlin string-template interpolation in the generated source)
 * - `\n` → `\\n`       (newline)
 * - `\r` → `\\r`       (carriage return)
 * - `\t` → `\\t`       (tab)
 */
private fun escapeKotlinString(value: String): String =
    value
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
        .replace("$", "\${'\$'}")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")

/**
 * Produces the Kotlin literal for `defaultValue = ...` in the generated `ConfigParam` call.
 *
 * STRING: producer stores bare value (surrounding quotes already stripped); re-wrap and
 * escape via [escapeKotlinString].
 * LONG: append `L` suffix.
 * FLOAT: append `f` suffix.
 * ENUM: rebuild as `enumTypeFqn.CONSTANT_NAME`.
 * BOOLEAN, INT, DOUBLE: emit raw.
 */
private fun FlagDescriptor.toDefaultLiteral(): String =
    when (valueType) {
        ValueType.STRING -> {
            "\"${escapeKotlinString(defaultValue)}\""
        }

        ValueType.LONG -> {
            "${defaultValue}L"
        }

        ValueType.FLOAT -> {
            "${defaultValue}f"
        }

        ValueType.ENUM -> {
            "$enumTypeFqn.$defaultValue"
        }

        ValueType.BOOLEAN, ValueType.INT, ValueType.DOUBLE -> {
            defaultValue
        }
    }
