package dev.androidbroadcast.featured.gradle

/**
 * Generates the `GeneratedFlagExtensions<Suffix>.kt` source file — internal extension
 * functions on `ConfigValues` for each declared flag.
 *
 * **Local Boolean flags** get an `is…Enabled()` extension returning the raw `Boolean`:
 * ```kotlin
 * internal fun ConfigValues.isDarkModeEnabled(): Boolean = getValueCached(GeneratedLocalFlags.darkMode).value
 * ```
 *
 * **Local non-Boolean flags** get a `get…()` extension returning the raw value type:
 * ```kotlin
 * internal fun ConfigValues.getMaxRetries(): Int = getValueCached(GeneratedLocalFlags.maxRetries).value
 * ```
 *
 * **Remote flags** get a `get…()` extension returning `ConfigValue<T>` so callers can
 * inspect the value source (DEFAULT / REMOTE / etc.):
 * ```kotlin
 * internal fun ConfigValues.getPromoBannerEnabled(): ConfigValue<Boolean> =
 *     getValueCached(GeneratedRemoteFlags.promoBannerEnabled)
 * ```
 *
 * Extensions are `internal` because no external production consumer depends on them — modules
 * that need `ConfigParam` values directly use `observe(GeneratedLocalFlags.x)` against the
 * now-`public` generated objects.
 *
 * **JVM class-name uniqueness:** `@file:JvmName` is intentionally absent — it is not
 * supported on Kotlin/Native targets. Instead, the emitted file is named
 * `GeneratedFlagExtensions<Suffix>.kt` where `<Suffix>` is derived from the Gradle module
 * path (e.g. `SampleFeatureCheckout`). The Kotlin compiler derives the JVM class name from
 * the file name, so `GeneratedFlagExtensionsSampleFeatureCheckoutKt` is unique per module
 * without any JVM-specific annotation.
 */
public object ExtensionFunctionGenerator {
    private const val PACKAGE = "dev.androidbroadcast.featured.generated"
    private const val CONFIG_VALUES_IMPORT = "dev.androidbroadcast.featured.ConfigValues"
    private const val CONFIG_VALUE_IMPORT = "dev.androidbroadcast.featured.ConfigValue"

    /**
     * Returns the emitted `.kt` file name for the given Gradle module path.
     *
     * The file-name suffix is derived by splitting the module path on all non-alphanumeric
     * characters and PascalCasing each segment, ensuring a valid Kotlin identifier without
     * any JVM-specific annotation. The Kotlin compiler derives the JVM class name from this
     * file name (e.g. `GeneratedFlagExtensionsSampleFeatureCheckoutKt`).
     *
     * Examples:
     * - `":app"` → `"GeneratedFlagExtensionsApp.kt"`
     * - `":feature:checkout"` → `"GeneratedFlagExtensionsFeatureCheckout.kt"`
     * - `":sample:feature-checkout"` → `"GeneratedFlagExtensionsSampleFeatureCheckout.kt"`
     */
    public fun fileName(modulePath: String): String = "GeneratedFlagExtensions${modulePath.modulePathToFileSuffix()}.kt"

    /**
     * Returns the legacy `@file:JvmName` value that was previously emitted into the source file.
     *
     * This function is retained for use by [ProguardRulesGenerator], which needs to reference
     * the JVM class name in `-assumevalues` rules.
     *
     * Examples: `":app"` → `"FeaturedApp_FlagExtensionsKt"`,
     * `":feature:checkout"` → `"FeaturedFeatureCheckout_FlagExtensionsKt"`.
     */
    public fun jvmFileName(modulePath: String): String = "Featured${modulePath.modulePathToIdentifier()}_FlagExtensionsKt"

    /**
     * Generates the full source text for the module-specific `GeneratedFlagExtensions<Suffix>.kt`.
     *
     * Returns an empty string if [entries] is empty.
     */
    public fun generate(
        entries: List<LocalFlagEntry>,
        modulePath: String,
    ): String {
        if (entries.isEmpty()) return ""
        val needsConfigValue = entries.any { !it.isLocal }
        val localObjectName = ConfigParamGenerator.localObjectName(modulePath)
        val remoteObjectName = ConfigParamGenerator.remoteObjectName(modulePath)

        return buildString {
            appendLine("// Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine()
            appendLine("package $PACKAGE")
            appendLine()
            appendLine("import $CONFIG_VALUES_IMPORT")
            if (needsConfigValue) appendLine("import $CONFIG_VALUE_IMPORT")
            val (localEntries, remoteEntries) = entries.partition { it.isLocal }
            if (localEntries.isNotEmpty()) {
                appendLine("import $PACKAGE.$localObjectName")
            }
            if (remoteEntries.isNotEmpty()) {
                appendLine("import $PACKAGE.$remoteObjectName")
            }
            appendLine()
            entries.forEach { entry ->
                appendLine(entry.toExtensionFunction(localObjectName, remoteObjectName))
            }
        }.trimEnd() + "\n"
    }

    private fun LocalFlagEntry.toExtensionFunction(
        localObjectName: String,
        remoteObjectName: String,
    ): String {
        val objectRef = if (isLocal) localObjectName else remoteObjectName
        return if (isLocal) {
            val funcName = extensionFunctionName()
            "internal fun ConfigValues.$funcName(): $type = getValueCached($objectRef.$propertyName).value\n"
        } else {
            // Remote flags always use get… regardless of type — the return is ConfigValue<T>,
            // so callers can inspect the value source.
            val funcName = "get${propertyName.capitalized()}"
            "internal fun ConfigValues.$funcName(): ConfigValue<$type> = getValueCached($objectRef.$propertyName)\n"
        }
    }
}
