package dev.androidbroadcast.featured.gradle

/**
 * A single `-checkdiscard` target: a class specification that must be absent from the
 * optimized release binary, together with the flag that guards it.
 *
 * @property flagKey The local boolean flag (default `false`) that guards [classSpec]. Used only
 *   for the generated comment so a failing check points at the responsible flag.
 * @property classSpec An R8/ProGuard class specification (e.g. `com.example.featurex.**`).
 */
public data class CheckDiscardEntry(
    public val flagKey: String,
    public val classSpec: String,
)

/**
 * Generates R8 `-checkdiscard` rules that **verify** flag-guarded code was actually removed
 * from the optimized release binary.
 *
 * This is the verification half of the dead-code-elimination story. [ProguardRulesGenerator]
 * emits `-assumevalues` rules that *cause* R8 to fold a local flag to its default and drop the
 * disabled branch; `-checkdiscard` then *asserts* the result — if any listed class survives,
 * R8 fails the build with `Discard checks failed` and prints the retention path (diagnose with
 * `-whyareyoukeeping`).
 *
 * Unit tests see the full classpath before R8 runs and `androidTest` is assembled without
 * minification, so without `-checkdiscard` nothing checks the final DEX. A forgotten DI
 * reference, a manifest entry, or reflection that keeps the feature alive is caught at build
 * time instead of shipping dead code (or worse, a still-reachable disabled feature).
 *
 * Each target is declared via `discard(...)` on a local boolean flag whose default is `false`
 * (see [FlagSpec.discard]); the matching `-assumevalues` rule is what makes the discard
 * guaranteed to hold in release builds.
 *
 * Example output for `boolean("new_checkout", default = false) { discard("com.example.checkout.newflow.**") }`:
 * ```proguard
 * # guarded by flag: new_checkout
 * -checkdiscard class com.example.checkout.newflow.** { *; }
 * ```
 *
 * The directive covers **code only** — it does not verify that resources are stripped.
 */
public object CheckDiscardRulesGenerator {
    /**
     * Generates `-checkdiscard` rules for all [entries].
     *
     * Entries with a blank [CheckDiscardEntry.classSpec] are skipped. Returns a blank string
     * when no entry contributes a rule, so the output file can be wired into R8 unconditionally
     * (an empty ProGuard configuration is a valid no-op).
     */
    public fun generate(entries: List<CheckDiscardEntry>): String {
        val valid =
            entries.mapNotNull { entry ->
                val spec = entry.classSpec.trim()
                if (spec.isEmpty()) null else entry.copy(classSpec = spec)
            }
        if (valid.isEmpty()) return ""

        val header =
            listOf(
                "# Auto-generated by Featured Gradle Plugin — do not edit manually.",
                "# -checkdiscard asserts these classes are absent from the optimized (R8) release binary.",
                "# Each target is guarded by a local boolean flag pinned to false via the generated",
                "# -assumevalues rule, so the flag-guarded code must be dead-code-eliminated.",
                "# If a target survives, R8 fails the build with \"Discard checks failed\" and the",
                "# retention path. Diagnose what keeps a class alive with -whyareyoukeeping.",
            )
        val rules =
            valid.map { entry ->
                "# guarded by flag: ${entry.flagKey}\n-checkdiscard class ${entry.classSpec} { *; }"
            }
        return (header + rules).joinToString("\n")
    }
}
