package dev.androidbroadcast.featured.gradle

/**
 * Generates `GeneratedLocalFlags.kt` and `GeneratedRemoteFlags.kt` — internal objects
 * containing one typed `ConfigParam` property per declared flag.
 *
 * Generated example for a local Boolean flag `dark_mode`:
 * ```kotlin
 * internal object GeneratedLocalFlags {
 *     val darkMode = ConfigParam<Boolean>("dark_mode", false, category = "UI")
 * }
 * ```
 *
 * These objects are `internal` — consumers access flags exclusively through the
 * generated extension functions in [ExtensionFunctionGenerator].
 */
public object ConfigParamGenerator {
    private const val PACKAGE = "dev.androidbroadcast.featured.generated"
    private const val CONFIG_PARAM_IMPORT = "dev.androidbroadcast.featured.ConfigParam"

    /**
     * Generates the Kotlin source for `GeneratedLocalFlags.kt` and
     * `GeneratedRemoteFlags.kt` as a pair.
     *
     * Returns a pair of `(localSource, remoteSource)`. Either may be an empty string
     * if there are no flags of that type.
     */
    public fun generate(entries: List<LocalFlagEntry>): Pair<String, String> {
        val local = entries.filter { it.isLocal }
        val remote = entries.filter { !it.isLocal }
        return generateObject(local, LocalFlagEntry.GENERATED_LOCAL_OBJECT) to
            generateObject(remote, LocalFlagEntry.GENERATED_REMOTE_OBJECT)
    }

    private fun generateObject(entries: List<LocalFlagEntry>, objectName: String): String {
        if (entries.isEmpty()) return ""
        return buildString {
            appendLine("// Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine("package $PACKAGE")
            appendLine()
            appendLine("import $CONFIG_PARAM_IMPORT")
            appendLine()
            appendLine("internal object $objectName {")
            entries.forEach { entry ->
                appendLine("    val ${entry.propertyName} = ${entry.toConfigParamExpression()}")
            }
            append("}")
        }
    }

    private fun LocalFlagEntry.toConfigParamExpression(): String {
        val typeArg = type
        val namedArgs = buildList {
            add("key = \"$key\"")
            add("defaultValue = ${formatDefault()}")
            if (description != null) add("description = \"$description\"")
            if (category != null) add("category = \"$category\"")
        }
        return "ConfigParam<$typeArg>(${namedArgs.joinToString(", ")})"
    }

    private fun LocalFlagEntry.formatDefault(): String =
        when (type) {
            "String" -> defaultValue  // already quoted by FlagContainer.string()
            "Long"   -> "${defaultValue}L"
            "Float"  -> "${defaultValue}f"
            else     -> defaultValue
        }
}
