package dev.androidbroadcast.featured.gradle

/**
 * Generates `GeneratedFlagExtensions.kt` — public extension functions on `ConfigValues`
 * for each declared flag.
 *
 * **Local Boolean flags** get an `is…Enabled()` extension returning the raw `Boolean`:
 * ```kotlin
 * fun ConfigValues.isDarkModeEnabled(): Boolean = getValue(GeneratedLocalFlags.darkMode).value
 * ```
 *
 * **Local non-Boolean flags** get a `get…()` extension returning the raw value type:
 * ```kotlin
 * fun ConfigValues.getMaxRetries(): Int = getValue(GeneratedLocalFlags.maxRetries).value
 * ```
 *
 * **Remote flags** get a `get…()` extension returning `ConfigValue<T>` so callers can
 * inspect the value source (DEFAULT / REMOTE / etc.):
 * ```kotlin
 * fun ConfigValues.getPromoBannerEnabled(): ConfigValue<Boolean> =
 *     getValue(GeneratedRemoteFlags.promoBannerEnabled)
 * ```
 *
 * The file uses `@file:JvmName(...)` with a module-derived suffix to guarantee unique
 * JVM class names when multiple modules apply the plugin — required for accurate
 * per-function ProGuard `-assumevalues` rules.
 */
public object ExtensionFunctionGenerator {
    private const val PACKAGE = "dev.androidbroadcast.featured.generated"
    private const val CONFIG_VALUES_IMPORT = "dev.androidbroadcast.featured.ConfigValues"
    private const val CONFIG_VALUE_IMPORT = "dev.androidbroadcast.featured.ConfigValue"

    /**
     * Returns the `@file:JvmName` value for the given Gradle module path.
     *
     * Examples: `":app"` → `"FeaturedApp_FlagExtensionsKt"`,
     * `":feature:checkout"` → `"FeaturedFeatureCheckout_FlagExtensionsKt"`.
     */
    public fun jvmFileName(modulePath: String): String =
        "Featured${modulePath.modulePathToIdentifier()}_FlagExtensionsKt"

    /**
     * Generates the full source text for `GeneratedFlagExtensions.kt`.
     *
     * Returns an empty string if [entries] is empty.
     */
    public fun generate(entries: List<LocalFlagEntry>, modulePath: String): String {
        if (entries.isEmpty()) return ""
        val jvmName = jvmFileName(modulePath)
        val needsConfigValue = entries.any { !it.isLocal }

        return buildString {
            appendLine("// Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine("@file:JvmName(\"$jvmName\")")
            appendLine()
            appendLine("package $PACKAGE")
            appendLine()
            appendLine("import $CONFIG_VALUES_IMPORT")
            if (needsConfigValue) appendLine("import $CONFIG_VALUE_IMPORT")
            val localEntries = entries.filter { it.isLocal }
            val remoteEntries = entries.filter { !it.isLocal }
            if (localEntries.isNotEmpty()) {
                appendLine("import $PACKAGE.${LocalFlagEntry.GENERATED_LOCAL_OBJECT}")
            }
            if (remoteEntries.isNotEmpty()) {
                appendLine("import $PACKAGE.${LocalFlagEntry.GENERATED_REMOTE_OBJECT}")
            }
            appendLine()
            entries.forEach { entry ->
                appendLine(entry.toExtensionFunction())
            }
        }.trimEnd() + "\n"
    }

    private fun LocalFlagEntry.toExtensionFunction(): String {
        val objectRef = if (isLocal) LocalFlagEntry.GENERATED_LOCAL_OBJECT else LocalFlagEntry.GENERATED_REMOTE_OBJECT
        return if (isLocal) {
            val returnType = jvmReturnType()
            val funcName = extensionFunctionName()
            "public fun ConfigValues.$funcName(): $returnType = getValue($objectRef.$propertyName).value\n"
        } else {
            val funcName = "get${propertyName.replaceFirstChar { it.uppercase() }}"
            "public fun ConfigValues.$funcName(): ConfigValue<$type> = getValue($objectRef.$propertyName)\n"
        }
    }

    private fun LocalFlagEntry.extensionFunctionName(): String {
        val capitalized = propertyName.replaceFirstChar { it.uppercase() }
        return if (type == "Boolean") "is${capitalized}Enabled" else "get$capitalized"
    }

    private fun LocalFlagEntry.jvmReturnType(): String = type
}
