package dev.androidbroadcast.featured.gradle

/**
 * Generates a Kotlin source file containing a `GeneratedFlagRegistrar` object that
 * calls `FlagRegistry.register(...)` for every `@LocalFlag`-annotated
 * [dev.androidbroadcast.featured.ConfigParam] discovered in the owning module.
 *
 * The generated class is KMP-safe: it imports only
 * `dev.androidbroadcast.featured.registry.FlagRegistry`, which is available in
 * `commonMain`. No Android-specific APIs are used.
 *
 * **AndroidX App Startup integration** is intentionally omitted. It can be added
 * as a separate Android-specific `Initializer` that delegates to
 * `GeneratedFlagRegistrar.register()` once AndroidX Startup support is implemented.
 *
 * **App-level aggregator** generation (a root-project object calling all module
 * registrars) is deferred as future work; per-module generation covers the primary
 * acceptance criterion.
 *
 * Usage: call [generate] with the list of scanned entries and the target package name.
 * The result should be written to
 * `build/generated/featured/<sourceSet>/GeneratedFlagRegistrar.kt` and the output
 * directory added to the Kotlin compilation source set.
 */
public object FlagRegistrarGenerator {
    private const val FLAG_REGISTRY_IMPORT = "dev.androidbroadcast.featured.registry.FlagRegistry"

    /**
     * Generates the `GeneratedFlagRegistrar.kt` source text.
     *
     * When [entries] is empty, or all entries lack a [LocalFlagEntry.kotlinReference],
     * the generated `register()` function body is empty — the file is still emitted so
     * that the compilation source set always contains a valid symbol.
     *
     * Entries whose [LocalFlagEntry.kotlinReference] is blank are skipped with a
     * `// TODO` comment so developers can spot flags that could not be resolved.
     *
     * @param entries Flag entries discovered by [LocalFlagScanner] for this module.
     * @param packageName Kotlin package for the generated file.
     *   Defaults to `"dev.androidbroadcast.featured.generated"`.
     */
    public fun generate(
        entries: List<LocalFlagEntry>,
        packageName: String = "dev.androidbroadcast.featured.generated",
    ): String =
        buildString {
            appendLine("package $packageName")
            appendLine()
            appendLine("import $FLAG_REGISTRY_IMPORT")
            appendLine()
            appendLine("// Auto-generated by the Featured Gradle plugin — do not edit manually.")
            appendLine("public object GeneratedFlagRegistrar {")
            appendLine("    /**")
            appendLine("     * Registers all `@LocalFlag`-annotated")
            appendLine("     * [dev.androidbroadcast.featured.ConfigParam] declarations from this module")
            appendLine("     * with [FlagRegistry].")
            appendLine("     *")
            appendLine("     * Call this once during app startup.")
            appendLine("     */")
            appendLine("    public fun register() {")
            entries.forEach { entry ->
                val ref = entry.kotlinReference
                if (ref.isNotBlank()) {
                    appendLine("        FlagRegistry.register($ref)")
                } else {
                    appendLine("        // TODO: register flag '${entry.key}' — property reference unavailable")
                }
            }
            appendLine("    }")
            append("}")
        }
}
