package dev.androidbroadcast.featured.gradle

/**
 * Generates `GeneratedFlagRegistrar.kt` — an object with a `register()` function that
 * calls `FlagRegistry.register(...)` for every flag declared in this module.
 *
 * The generated references point to the objects produced by [ConfigParamGenerator]:
 * ```kotlin
 * public object GeneratedFlagRegistrar {
 *     public fun register() {
 *         FlagRegistry.register(GeneratedLocalFlags.darkMode)
 *         FlagRegistry.register(GeneratedRemoteFlags.newCheckout)
 *     }
 * }
 * ```
 *
 * This file is KMP-safe: it imports only `dev.androidbroadcast.featured.registry.FlagRegistry`
 * which is available in `commonMain`.
 */
public object FlagRegistrarGenerator {
    private const val FLAG_REGISTRY_IMPORT = "dev.androidbroadcast.featured.registry.FlagRegistry"
    private const val LOCAL_FLAGS_IMPORT =
        "dev.androidbroadcast.featured.generated.${LocalFlagEntry.GENERATED_LOCAL_OBJECT}"
    private const val REMOTE_FLAGS_IMPORT =
        "dev.androidbroadcast.featured.generated.${LocalFlagEntry.GENERATED_REMOTE_OBJECT}"

    /**
     * Generates the `GeneratedFlagRegistrar.kt` source text.
     *
     * When [entries] is empty the `register()` body is empty but the file is still emitted
     * so the compilation source set always contains a valid symbol.
     *
     * @param entries All flag entries for this module (local + remote).
     * @param packageName Package for the generated file.
     */
    public fun generate(
        entries: List<LocalFlagEntry>,
        packageName: String = "dev.androidbroadcast.featured.generated",
    ): String =
        buildString {
            appendLine("// Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine("package $packageName")
            appendLine()
            appendLine("import $FLAG_REGISTRY_IMPORT")
            if (entries.any { it.isLocal }) appendLine("import $LOCAL_FLAGS_IMPORT")
            if (entries.any { !it.isLocal }) appendLine("import $REMOTE_FLAGS_IMPORT")
            appendLine()
            appendLine("public object GeneratedFlagRegistrar {")
            appendLine("    /**")
            appendLine("     * Registers all flags declared in this module with [FlagRegistry].")
            appendLine("     * Call this once during app startup.")
            appendLine("     */")
            appendLine("    public fun register() {")
            entries.forEach { entry ->
                val ref = entry.kotlinReference
                if (ref.isNotBlank()) {
                    appendLine("        FlagRegistry.register($ref)")
                } else {
                    appendLine("        // TODO: register flag '${entry.key}' — property reference unavailable")
                }
            }
            appendLine("    }")
            append("}")
        }
}
