package dev.androidbroadcast.featured.gradle

private const val GENERATED_PACKAGE = "dev.androidbroadcast.featured.generated"
private const val HEADER = "// Auto-generated by featured-gradle-plugin — do not edit"

/**
 * Generates Kotlin source files for Kotlin/Native iOS targets from
 * `@LocalFlag`-annotated [dev.androidbroadcast.featured.ConfigParam] declarations.
 *
 * Two files are produced:
 * - **`commonMain`** — `expect val` declarations (one per flag).
 * - **`iosMain`** — `actual const val` declarations whose values match each flag's
 *   `defaultValue`. LLVM can inline these constants and eliminate dead branches in
 *   release iOS framework builds.
 *
 * String values are wrapped in double-quotes; all other primitive types are emitted
 * verbatim (matching Kotlin literal syntax for Boolean, Int, Long, Double, Float).
 *
 * **Enum flags are not supported** — Kotlin `const val` only accepts primitive types
 * and `String`. Enum entries are silently skipped in both [generate] and [generateExpect].
 */
public object IosConstValGenerator {
    /**
     * Generates the `iosMain` Kotlin source file containing `actual const val`
     * declarations for every entry in [entries].
     *
     * Enum-typed entries (detected via [LocalFlagEntry.isEnum]) are excluded because
     * `const val` does not support enum types.
     *
     * Returns a blank string when [entries] is empty or all entries are enums.
     */
    public fun generate(entries: List<LocalFlagEntry>): String {
        val eligible = entries.filterNot { it.isEnum }
        if (eligible.isEmpty()) return ""
        return buildString {
            appendLine(HEADER)
            appendLine("package $GENERATED_PACKAGE")
            appendLine()
            eligible.forEach { entry ->
                appendLine(actualDeclaration(entry))
            }
        }
    }

    /**
     * Generates the `commonMain` Kotlin source file containing `expect val`
     * declarations for every entry in [entries].
     *
     * Enum-typed entries (detected via [LocalFlagEntry.isEnum]) are excluded because
     * `const val` does not support enum types.
     *
     * Returns a blank string when [entries] is empty or all entries are enums.
     */
    public fun generateExpect(entries: List<LocalFlagEntry>): String {
        val eligible = entries.filterNot { it.isEnum }
        if (eligible.isEmpty()) return ""
        return buildString {
            appendLine(HEADER)
            appendLine("package $GENERATED_PACKAGE")
            appendLine()
            eligible.forEach { entry ->
                appendLine("public expect val ${entry.key}: ${entry.type}")
            }
        }
    }

    private fun actualDeclaration(entry: LocalFlagEntry): String {
        val literal =
            if (entry.type == "String") {
                "\"${entry.defaultValue}\""
            } else {
                entry.defaultValue
            }
        return "public actual const val ${entry.key}: ${entry.type} = $literal"
    }
}
