package dev.androidbroadcast.featured.gradle

/**
 * Generates ProGuard/R8 `-assumevalues` rules for **local** `ConfigParam` flags.
 *
 * Each local flag is backed by a generated extension function on `ConfigValues`
 * (see [ExtensionFunctionGenerator]). By telling R8 the exact return value of each
 * extension, it can propagate the constant through call sites and eliminate dead branches.
 *
 * Example output for a Boolean flag `dark_mode = false` in module `:feature:ui`:
 * ```proguard
 * -assumevalues class dev.androidbroadcast.featured.generated.FeaturedFeatureUi_FlagExtensionsKt {
 *     boolean isDarkModeEnabled(dev.androidbroadcast.featured.ConfigValues) return false;
 * }
 * ```
 *
 * Only **local** flags are covered — remote flag values are resolved at runtime and
 * cannot be assumed at build time.
 *
 * Supported return types: `boolean`, `int`, `long`, `float`, `double`, `java.lang.String`.
 */
public object ProguardRulesGenerator {
    private const val PACKAGE = "dev.androidbroadcast.featured.generated"
    private const val CONFIG_VALUES_TYPE = "dev.androidbroadcast.featured.ConfigValues"

    /**
     * Generates ProGuard `-assumevalues` rules for all local flags in [entries].
     *
     * [modulePath] is the Gradle module path (e.g. `":feature:ui"`) used to derive
     * the JVM class name of the generated extensions file via [ExtensionFunctionGenerator.jvmFileName].
     *
     * Returns a blank string when [entries] contains no local flags with a supported type.
     */
    public fun generate(
        entries: List<LocalFlagEntry>,
        modulePath: String,
    ): String {
        val localEntries = entries.filter { it.isLocal && jvmType(it.type) != null }
        if (localEntries.isEmpty()) return ""

        val className = "$PACKAGE.${ExtensionFunctionGenerator.jvmFileName(modulePath)}"

        return buildString {
            appendLine("# Auto-generated by Featured Gradle Plugin — do not edit manually.")
            appendLine("# Local flags are assumed to be at their default values in release builds.")
            appendLine("-assumevalues class $className {")
            localEntries.forEach { entry ->
                val jvmType = jvmType(entry.type) ?: return@forEach
                val funcName = extensionFunctionName(entry)
                val returnValue = proguardLiteral(entry)
                appendLine("    $jvmType $funcName($CONFIG_VALUES_TYPE) return $returnValue;")
            }
            append("}")
        }
    }

    private fun jvmType(kotlinType: String): String? =
        when (kotlinType) {
            "Boolean" -> "boolean"
            "Int" -> "int"
            "Long" -> "long"
            "Float" -> "float"
            "Double" -> "double"
            "String" -> "java.lang.String"
            else -> null
        }

    private fun extensionFunctionName(entry: LocalFlagEntry): String {
        val capitalized = entry.propertyName.replaceFirstChar { it.uppercase() }
        return if (entry.type == "Boolean") "is${capitalized}Enabled" else "get$capitalized"
    }

    private fun proguardLiteral(entry: LocalFlagEntry): String =
        when (entry.type) {
            "String" -> entry.defaultValue

            // already quoted (e.g. `"hello"`)
            "Long" -> entry.defaultValue.trimEnd('L', 'l')

            "Float" -> entry.defaultValue.trimEnd('f', 'F')

            else -> entry.defaultValue
        }
}
