package dev.androidbroadcast.featured.gradle

/**
 * Generates an Xcode `.xcconfig` file containing `SWIFT_ACTIVE_COMPILATION_CONDITIONS`
 * entries for `@LocalFlag`-annotated `ConfigParam` properties whose `defaultValue` is `false`.
 *
 * Only Boolean flags frozen to `false` at release build time generate a `DISABLE_` condition,
 * enabling Swift compiler dead code elimination at entry points. Flags with `defaultValue = true`,
 * non-boolean flags, and `@RemoteFlag` declarations are intentionally excluded.
 *
 * **Key transformation:** flag keys are converted from `snake_case` or `camelCase` to
 * `SCREAMING_SNAKE_CASE` and prefixed with `DISABLE_`. For example:
 * - `new_checkout` → `DISABLE_NEW_CHECKOUT`
 * - `experimentalUi` → `DISABLE_EXPERIMENTAL_UI`
 */
public object XcconfigGenerator {

    /**
     * Generates an xcconfig content string from [entries].
     *
     * Returns a blank string when no qualifying entries exist (Boolean type,
     * `defaultValue == "false"`). Otherwise returns a file with a header comment
     * and a single `SWIFT_ACTIVE_COMPILATION_CONDITIONS` assignment.
     */
    public fun generate(entries: List<LocalFlagEntry>): String {
        val disabled = entries.filter { it.type == "Boolean" && it.defaultValue == "false" }
        if (disabled.isEmpty()) return ""

        val conditions = disabled.joinToString(" ") { "DISABLE_${it.key.toScreamingSnakeCase()}" }

        return buildString {
            appendLine("# Auto-generated by featured-gradle-plugin — do not edit")
            appendLine("# Include this file in your Xcode Release configuration")
            append("SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) $conditions")
        }
    }

    /**
     * Converts a `snake_case` or `camelCase` key to `SCREAMING_SNAKE_CASE`.
     *
     * Steps:
     * 1. Insert `_` before every uppercase letter that follows a lowercase letter (camelCase split).
     * 2. Replace any non-alphanumeric runs with `_`.
     * 3. Uppercase the result.
     */
    private fun String.toScreamingSnakeCase(): String =
        replace(Regex("([a-z])([A-Z])"), "$1_$2")
            .replace(Regex("[^A-Za-z0-9]+"), "_")
            .uppercase()
}
